<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ConfigsSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$data = array(
		    array(
		        "name"=>"USE_GOOGLE_TRANSLATE",
		        "value"=>"0",
		        "comment"=>"Utiliser la traduction google pour traduire le site.",
		        "readonly"=> true,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"GOOGLE_INDEXED",
		        "value"=>"0",
		        "comment"=>"Authoriser l'autorisation du site par Les bots de google inc.",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"GOOGLE_TAG_MANAGER_ID",
		        "value"=>null,
		        "comment"=>"Configurer l'Id du tag google manager.",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'text',
		    ),
		    array(
		        "name"=>"FORCE_HTTPS_PROTOCOL",
		        "value"=>"1",
		        "comment"=>"Activer la rédirection HTTPS automatique sur votre site",
		        "readonly"=>true,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"SITE_NAME",
		        "value"=>"Site Name ®",
		        "comment"=>"Configurer le nom du site qui sera affiché aux clients",
		        "readonly"=> false,
		        'auto_set' => "app.name|mail.from.name",
		        'input_type' => 'text',
		    ),
		    array(
		        "name"=>"DEFAULT_CONVERT_CURRENCY",
		        'value' => "USD",
		        'comment' => "La devise monétaire par defaut ( pour les conversions ).",
		        'readonly' => false,
		        'auto_set' => null,
		        'input_type' => 'text',
		    ),
		    array(
		        "name"=>"DEFAULT_SITE_LANGUAGE",
		        'value' => "en",
		        'comment' => "La langue par defaut du site.",
		        'readonly' => false,
		        'auto_set' => 'app.locale',
		        'input_type' => 'text',
		    ),
		    array(
		        "name"=>"SITE_ADDRESS",
		        "value"=>"R. Barata Salgueiro 5",
		        "comment"=>"Configurer l'adresse de l'emplacement du site qui sera affiché aux clients",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'textarea',
		    ),
		    array(
		        "name"=>"SITE_ADDRESS_ALT",
		        "value"=>"",
		        "comment"=>"Configurer l'adresse alternative de l'emplacement du site qui sera affiché aux clients",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'textarea',
		    ),
		    array(
		        "name"=>"SITE_EMAIL",
		        "value"=>"contact@sitedomain.com",
		        "comment"=>"Configurer l'email du site qui sera affiché aux clients",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'email',
		    ),
		    array(
		        "name"=>"SITE_WWW",
		        "value"=>"sitedomain.com",
		        "comment"=>"Configurer l'adresse www du site qui sera affiché aux clients",
		        "readonly"=> true,
		        'auto_set' => null,
		        'input_type' => 'text',
		    ),
		    array(
		        "name"=>"SITE_PHONE",
		        "value"=>"+xx0000000000",
		        "comment"=>"Configurer le numéro de téléphone du site qui sera affiché aux clients",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'tel',
		    ),
		    array(
		        "name"=>"SITE_PHONE_ALT",
		        "value"=>null,
		        "comment"=>"Configurer le numéro de téléphone 2 du site qui sera affiché aux clients",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'tel',
		    ),
		    array(
		        "name"=>"SITE_WHATSAPP",
		        "value"=>null,
		        "comment"=>"Configurer le numéro whatsapp qui sera affiché aux clients",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'tel',
		    ),
		    array(
		        "name"=>"TEAG",
		        "value"=>"1.63",
		        "comment"=>"Taux d'intérêt appliqué sur le site.",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'text',
		    ),
		    array(
		        "name"=>"AUTHOR_NAME",
		        "value"=>"Author Company Ltd.",
		        "comment"=>"Informations de l'auteur du site",
		        "readonly"=>true,
		        'auto_set' => null,
		        'input_type' => 'text',
		    ),
		    array(
		        "name"=>"AUTHOR_EMAIL",
		        "value"=>"support@site-internet.com",
		        "comment"=>"Informations de l'auteur du site",
		        "readonly"=>true,
		        'auto_set' => null,
		        'input_type' => 'email',
		    ),
		    array(
		        "name"=>"WEBMASTER_NAME",
		        "value"=>"Author Company Ltd.",
		        "comment"=>"Informations du webmaster",
		        "readonly"=>true,
		        'auto_set' => null,
		        'input_type' => 'text',
		    ),
		    array(
		        "name"=>"WEBMASTER_EMAIL",
		        "value"=>"support@site-internet.com",
		        "comment"=>"Informations du webmaster",
		        "readonly"=>true,
		        'auto_set' => null,
		        'input_type' => 'email',
		    ),
		    array(
		        "name"=>"SITE_PRIMARY_COLOR",
		        "value"=>"#fe696a",
		        "comment"=>"La couleur principale du site et des emails",
		        "readonly"=> true,
		        'auto_set' => null,
		        'input_type' => 'text',
		    ),
		    array(
		        "name"=>"CRISP_CHAT_WIDGET_ID",
		        "value"=>"",
		        "comment"=>"Id du widget de crisp",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'text',
		    ),
		    array(
		        "name"=>"PAGINATION_PER_PAGE",
		        "value"=>"15",
		        "comment"=>"Nombre d'items à afficher par page",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'number',
		    ),
		    array(
		        "name"=>"CREATED_DATE",
		        "value"=>"2011",
		        "comment"=>"Date de création du site",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'number',
		    ),
		    array(
		        "name"=>"CUSTOMER_PASSWORD_CHANGING_COST",
		        "value"=>"0",
		        "comment"=>"Facturé le client lorsqu'il change son mot de passe",
		        "readonly"=> true,
		        'auto_set' => null,
		        'input_type' => 'number',
		    ),
		    array(
		        "name"=>"CUSTOMER_RECIPIENT_ADDING_COST",
		        "value"=>"0",
		        "comment"=>"Facturé le client lorsqu'il ajoute un nouveau bénéficiaire",
		        "readonly"=> true,
		        'auto_set' => null,
		        'input_type' => 'number',
		    ),
		    array(
		        "name"=>"CUSTOMER_TRANSFERT_ADDING_COST",
		        "value"=>"0",
		        "comment"=>"Facturé le client lorsqu'il démarre un transfert de fonds",
		        "readonly"=> true,
		        'auto_set' => null,
		        'input_type' => 'number',
		    ),
		    array(
		        "name"=>"NEW_CUSTOMER_BALANCE",
		        "value"=>"0",
		        "comment"=>"Solde initial des nouveaux clients après leur inscription sur le site.",
		        "readonly"=> true,
		        'auto_set' => null,
		        'input_type' => 'number',
		    ),
		    array(
		        "name"=>"BLOCK_CUSTOMER_ON_TRANSFER_PAGE",
		        "value"=>"1",
		        "comment"=>"Lorsque un client à un transfert bancaire en cours on le bloque sur la page du transfert ou pas ( selon le cas ).",
		        "readonly"=>false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"FIRST_LATENCE_OF_TRANSFERT",
		        "value"=>"5",
		        "comment"=>"Attendre cet intervalle de temps ( en minutes ) avant d'afficher le premier frais",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'number',
		    ),
		    array(
		        "name"=>"SHOW_PAID_TRANSFERT_CODE",
		        "value"=>"0",
		        "comment"=>"Afficher le code apres que le frais soit validé",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"ALLOW_WITHDRAWALS_TO_PAYPAL",
		        "value"=>"1",
		        "comment"=>"Autoriser les virements vers un compte paypal",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"ALLOW_WITHDRAWALS_TO_BANK",
		        "value"=>"1",
		        "comment"=>"Autoriser les virements vers un compte bancaire",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"ALLOW_WITHDRAWALS_TO_CARD",
		        "value"=>"1",
		        "comment"=>"Autoriser les virements vers une carte de crédit / débit",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"SHOW_PHONENUMBER_ON_HOMEPAGE",
		        "value"=>"1",
		        "comment"=>"Afficher le numéro de téléphone sur la page d'accueil",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"LOGIN_USING_ACCOUNTNUMBER_AND_BIRTHDATE",
		        "value"=>"0",
		        "comment"=>"Se connecter en utilisant le numero de compte du client et sa date d'anniversaire.",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"LOGIN_USING_EMAIL_AND_PASSWORD",
		        "value"=>"1",
		        "comment"=>"Se connecter en utilisant email du client et son mot de passe.",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"LOGIN_USING_ACCOUNTNUMBER_AND_PASSWORD",
		        "value"=>"0",
		        "comment"=>"Se connecter en utilisant le numero de compte du client et son mot de passe.",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"TRANSFER_CODE_LENGTH",
		        "value"=>"6",
		        "comment"=>"La longueur exacte du code de transfert.",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'number',
		    ),
		    array(
		        "name"=>"AUTO_VERIFY_NEW_PAYPAL_ACCOUNT",
		        "value"=>"0",
		        "comment"=>"Marqué chaque nouveau compte paypal comme vérifié.",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"AUTO_VERIFY_NEW_BANK_CARD",
		        "value"=>"0",
		        "comment"=>"Marqué chaque nouvelle carte bancaire comme vérifiée.",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"AUTO_VERIFY_NEW_RECIPIENT_ACCOUNT",
		        "value"=>"0",
		        "comment"=>"Marqué chaque nouveau compte bénéficiaire comme vérifié.",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    ),
		    array(
		        "name"=>"BLOCK_ACCESS_TO_UNAUTHORIZED_COUNTRIES",
		        "value"=>"0",
		        "comment"=>"bloquer l'accès du site aux pays qui ne sont pas activé dans l'administration.",
		        "readonly"=> false,
		        'auto_set' => null,
		        'input_type' => 'boolean',
		    )
		);
		
		foreach ($data as $name => $item) {
			\App\Models\Config::create([
				'name' 		=> $item['name'],
				'value' 	=> $item['value'],
				'comment' 	=> $item['comment'],
				'readonly' 	=> $item['readonly'],
				'auto_set' 	=> !empty($item['auto_set']) ? $item['auto_set'] : null,
				'input_type' => $item['input_type'],
			]);
		}
	}
}
