<?php

return array(
	"TRAD_1" => "(WEBSITE_NAME) aims to provide the best online experience during your visit to our site, which is why we use certain types of \"cookies\".",
	"TRAD_2" => "What are cookies?",
	"TRAD_3" => "Cookies are packets of information sent by a web server (in this case, by this site) to the visitor's Internet browser, stored on their computer, and sent to the server each time they access the next site. Therefore, for the full use of this site, you are advised to configure the browser to accept the receipt of cookies.",
	"TRAD_4" => "Why do we use them?",
	"TRAD_5" => "Cookies are used to facilitate navigation in the site and the correct use and for statistical purposes, to know which areas of the site have been visited to make improvements and updates based on usage habits. The cookies used on this site do not allow the acquisition of personal identification data of users. The user can then browse the site without disclosing his personal information.",
	"TRAD_6" => "Type of cookies used",
	"TRAD_7" => "\"Session cookies\" - reside exclusively in the memory of the user\\\'s computer and are erased once the browser is closed. Use is strictly limited to the transmission of session identifiers, consisting of random numbers generated by the server, necessary to allow a site to be secure and efficient.",
	"TRAD_8" => "These cookies allow us to collect anonymous information about the pages visited by a user and how you use our site in order to improve navigation in the future and to determine the source of possible error messages. For example, collect information on pages visited, number of visits, visitor's browser.",
	"TRAD_9" => "Third party cookies",
	"TRAD_10" => "Our site may, from time to time, contain links to third party websites. If you follow a link to these third-party sites, please review their privacy policies, about cookies and how they are managed before providing any personal data on these sites.",
	"TRAD_11" => "How to manage cookie settings?",
	"TRAD_12" => "To ensure that you make the best use of our website, we recommend that you accept cookies. Most Internet browsers are initially configured to accept cookies. You can, at any time, configure your browser to accept all cookies. Additionally, you can set preferences for the browser to be notified each time a cookie is stored on your computer. Please note that invalid cookies may prevent normal and optimal use of the site.",
	"TRAD_13" => "Changes to this Policy",
	"TRAD_14" => "This policy may change over time and is also linked to the entry into force of new regulations."
);